# Site settings
title: Vinics
email: i@vinics.com.au
description: > # this means to ignore newlines until "baseurl:"
  We make IT work for you. We pride ourselves in partnering you to your potential.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vinics.com.au" # the base hostname & protocol for your site
twitter_username: vyasp
github_username:  vinicsinc
published: false
# Build settings
markdown: kramdown
